[build]
  publish = "public"
  command = "hugo --minify"

[build.environment]
  HUGO_VERSION = "0.120.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[redirects]]
  from = "/search"
  to = "/"
  status = 301

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404